<!-- <h2><?php echo $this->getHelloWorldTxt(); ?></h2> -->

<form>
<center><h1>CONTACT US FORM</h1></center>
<label for="name">Name:</label>
<input type="text" name="name" placeholder="Name"/> 
<br/>
<label for="email">Email:</label>
<input type="email" name="email" placeholder="Email"/> 
<br/>
<label for="query">Query:</label>
<textarea placeholder="Enter your query..."></textarea>
<br/>
<input type="submit" name="submit">
</form>
